language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
before_script: composer install
script:
    - vendor/bin/phpunit tests/
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
notifications:
  email: false
